// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMqV72mEVoBZmiWohWVCMXMgjnepev7xo',
    appId: '1:476626016703:web:1097ff53cdf15cc3aee90a',
    messagingSenderId: '476626016703',
    projectId: 'chat-app-24dca',
    authDomain: 'chat-app-24dca.firebaseapp.com',
    storageBucket: 'chat-app-24dca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMdePKGv4-jG1GhW06eTC_YcSzZ1rmoxo',
    appId: '1:476626016703:android:ed31e1715efa9623aee90a',
    messagingSenderId: '476626016703',
    projectId: 'chat-app-24dca',
    storageBucket: 'chat-app-24dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwtAglpm8qkSsAR2r0d3o7Nq16h9S1qlc',
    appId: '1:476626016703:ios:be712e9159288052aee90a',
    messagingSenderId: '476626016703',
    projectId: 'chat-app-24dca',
    storageBucket: 'chat-app-24dca.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMessengerApp',
  );
}
